### ISSUE TITLE
Navigation keyboard and consecutive days bug

### ISSUE THREAD

**Issue by BenevidesLecontes** [jckdrpr/react-horizontal-timeline#1]
Hi! thanks for this plugin, as i saw in original plugin, they use keyboard to navigate, and in yours it doesn't work. And if i use for example 20/02/2016 and 21/02/2016, the timeline goes crazy, both in yours and codyhouse plugin. Did you know how to solve this?
Sorry for my english.

**Comment by jck-d-rpr** [comment]
The format is like mm/dd/yyyy so can you try 02/20/1016 and 02/21/2016 and report your findings? 
and about the keyboard part I haven't implemented that (and scrolling via touch) at the moment. I am planning to look into it but won't guarantee anything.PR's are more than welcome.

**Comment by jckdrpr** [comment]
Closing this issue as now there is keyboard navigation and I haven't seen the consecutive days bug.
