### ISSUE TITLE
Same Date Different Content

### ISSUE THREAD

**Issue by Shadowman4205** [jckdrpr/react-horizontal-timeline#20]
Hello,

is there fast implementation to make same date appear once in timeline and make it appear on content section as Content1, Content2 etc.

Thanks

**Comment by Nickman87** [comment]
Could you elaborate a bit? What is it exactly you want to accomplish?
The timeline just represents a set of dates and tells you which date was clicked. Linking the date to content is something you have to do in your own code.

**Comment by Shadowman4205** [comment]
For example i have data , two items (item1, item2) has got same date. In the time line
it appear like this
----------item1(16/02/2017)-------item2(16/02/2017)--------------
                 Content1                             Content2
i want make it like this

----------item1,2(16/02/2017)--------------------------------  <-unique date By selecting this i want take
              Content1, Content2

**Comment by Nickman87** [comment]
@Shadowman4205 You could use the `getLabel` prop on the timeline to customise the label that is shown?
so, preprocess your data to make all the doubles unique and provide the correct label, based on both data points, trough the getLabel method.
