### ISSUE TITLE
require react-horizontal-timeline in a react component

### ISSUE THREAD

**Issue by raphael-thibierge** [jckdrpr/react-horizontal-timeline#3]
I did : 
` npm install react-horizontal-timeline`

Then I added `var TimeLine = require('react-horizontal-timeline');` in a one of my React Component and I get this error while doing `npm start` :

`Cannot find module '!!./../../node_modules/css-loader/index.js!./timeline.css' from 'myRepository/node_modules/react-horizontal-timeline/dist'`

Any idea ?
Thanks

**Comment by jckdrpr** [comment]
I never faced the this issue still I have updated the module in which I have completely removed the css file. Can you try out the updated module?
