### ISSUE TITLE
Warning: Unknown prop `_radiumDidResolveStyles`

### ISSUE THREAD

**Issue by Donaldini** [jckdrpr/react-horizontal-timeline#4]
![screen shot 2016-07-19 at 16 19 22](https://cloud.githubusercontent.com/assets/2185680/16953153/41867a7a-4dcc-11e6-872a-724d62da26e2.png)

After Googling, this appears to be an issue in Radium which is fixed in the current version: 
https://github.com/FormidableLabs/radium/issues/759

**Comment by jckdrpr** [comment]
I have updated radium's version. Thank you for reporting and solving this issue.
