### ISSUE TITLE
Inline styling difficult to customize

### ISSUE THREAD

**Issue by Donaldini** [jckdrpr/react-horizontal-timeline#5]
I noticed all the styling is inline on the HTML elements themselves.
Isn't it better to just use a CSS file to put all the styling in.

I'm asking because i'm trying to integrate this component and customising the styling is rather difficult in regular css. It pretty much requires me to either fork this component or use _!importants_ all the time.

**Comment by jckdrpr** [comment]
There is no particular reason of doing. All the styling that I could think of that one would  want to change can be changed by passing a style object.

As I Do not know what your use case is you can feel free to contribute.

**Comment by Donaldini** [comment]
ok, i'm trying to use your styles object, which I didn't notice before, sorry :-)

Here are some issues i'm having:

- Our **colors** are in sass variables which I can't use in the JSX
- I get errors on the **maxSize** property for using '90%' as a value because i'm using a string instead of the required number.

Here's a screenshot of the mockup we have using the jQuery version of the timeline (right side) and on the left is what I currently have with the React version.

![horizontal timeline](https://cloud.githubusercontent.com/assets/2185680/16984282/598010de-4e79-11e6-9e3a-a1b4bf75536c.png)

**Note**
I do still have an issue with a width property that doesn't want to be set because of _NaN_. I'm not entirelly sure what the reason for that is.

**JSX File**
```
import React from 'react';
import HorizontalTimeline from 'react-horizontal-timeline';

const VALUES = ['01/01/2016', '03/02/2016', '05/03/2016', '21/05/2016', '12/08/2016', '15/10/2016'];

export default class Timeline extends React.Component {
    state = {
        value: 0,
        previous: 0
    };

    render() {
        return (
          <div className="timeline-component">
            <HorizontalTimeline
                indexClick={(index) => {
                    this.setState({
                        value: index,
                        previous: this.state.value
                    });
                }}
                values={VALUES}
                styles={{
                    background: 'white',                // Should be $col_white
                    foreground: 'rgb(0, 157, 217)',     // Should be $col_blue-2
                    outline: 'rgb(223, 223, 223)',      // Should be $col_...
                    maxSize: '90%'                      // Not allowed, only number
                }}
            />
          </div>
        );
    }
}
```

I have been able to fix some styling issues by applying extra CSS, but as seen in the code below, this isn't very good code when there aren't any classes.

![image](https://cloud.githubusercontent.com/assets/2185680/16984467/65e7bd26-4e7a-11e6-8f36-fcafbb307d64.png)


```
.timeline-component {

  // Overwriting styling of react-horizontal-timeline component
  > div {
    margin: 0 !important;

    > div {
      margin: 0 auto !important;
      height: 80px !important;

      ul:first-of-type {
        li:first-child {
          background-image: linear-gradient(to right, $col_white, rgba(248, 248, 248, 0)) !important;
        }

        li:last-child {
          background-image: linear-gradient(to left, $col_white, rgba(248, 248, 248, 0)) !important;
        }
      }
    }
  }

  .events-wrapper {
    > div {
      background: none !important;
    }
  }
}
```

**Comment by jckdrpr** [comment]
Can you please tell me what happens if you just do ?
```
        <HorizontalTimeline
          index={this.state.value}
          indexClick={(index) => {
            this.setState({ value: index, previous: this.state.value });
          }}
          values={ this.dates } />
```
Are you able to see the the timeline properly?
From what it looks like I think you are missing bootstrap and react-motion?
It's just speculation on my part will look at it closely once I leave from office.

And I am not familier with sass so I will do some digging into that to see if we can use that in jsx and will also take a look at maxSize?

**Comment by Donaldini** [comment]
I had to make a tiny adjustment to the values, because there was no data in it, but still resulted in this:

![image](https://cloud.githubusercontent.com/assets/2185680/16985285/ae4b4b8c-4e7f-11e6-96cd-df07c02e67f4.png)

**Code**
```
import React from 'react';
import HorizontalTimeline from 'react-horizontal-timeline';

const VALUES = ['01/01/2016', '03/02/2016', '05/03/2016', '21/05/2016', '12/08/2016', '15/10/2016'];

export default class Timeline extends React.Component {
    state = {
        value: 0,
        previous: 0
    };

    render() {
        return (
            <HorizontalTimeline
                index={this.state.value}
                indexClick={(index) => {
                    this.setState({
                        value: index,
                        previous: this.state.value
                    });
                }}
                values={ VALUES }
            />
        );
    }
}
```

**Comment by jckdrpr** [comment]
Do you have [react-motion](https://github.com/chenglou/react-motion)?

**Comment by Donaldini** [comment]
Yup, version 0.4.4

**Comment by jckdrpr** [comment]
I think I have found the problem.
try `const VALUES = [ '01/01/2016', '02/03/2016', '03/05/2016', '05/21/2016', '08/12/2016', '10/15/2016' ];`
instead of `const VALUES = ['01/01/2016', '03/02/2016', '05/03/2016', '21/05/2016', '12/08/2016', '15/10/2016'];`

The format for dates is mm/dd/yyyy. lol

**Comment by Donaldini** [comment]
Yes, that seems to have done the trick. I did use the ISO8601 date formatting in the end and that also worked.

``
const VALUES = ['2016-01-01', '2016-02-03', '2016-03-05', '2016-05-21', '2016-08-12', '2016-10-15'];
``

Wouldn't it be better to display this as a default in the readme.md on the front page?

[Wikipedia: ISO 8601  – Representation of dates and times](https://en.wikipedia.org/wiki/ISO_8601)

**Comment by jckdrpr** [comment]
Anything the the JS Date constructer will accept will work as internally I am just doing `...new Date(dateString)...` . Also there have been a few changes to the component (like auto adjusting to the size of the viewport)  in it's latest release, check it out to see if it suits your usecase better. 

There is still no way of accepting sass variables and I don't think it should be a part of this component as it is to specific to a particular usecase. So apologies but you will have to figure this part out.

You are right about the readme I am going to update it with more details.

**Comment by Donaldini** [comment]
Thanks!
I'll be following Nickman87's changes to the component.
